apiVersion: v2
name: pagopa-fdr-tech-support-api
description: Technical support api
type: application
version: "0.60.0"
appVersion: "1.1.6-1-PIDM-1502-fix-xml-flow-retrieve"
dependencies:
  - name: microservice-chart
    version: 8.0.2
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
